yeild_apple  = w11 * temp + w12 * rainfall + w13 * humidity + b1



yeild_orange = w21 * temp + w22 * rainfall + w23 * humidity + b2


In [1]:
import numpy as np
import torch
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [2]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [3]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [4]:
# Weights and biases
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[ 2.0339, -0.0799, -0.0543],
        [ 1.0528,  0.5236,  0.5564]], requires_grad=True)
tensor([-0.6229,  1.7652], requires_grad=True)


In [5]:
def model(x):
    return x @ w.t() + b # x[5,3][3,2] 5,2
preds = model(inputs)

In [6]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()
loss = mse(preds, targets)

In [7]:
print(loss)
print(w)
print(w.grad)
print(b)
print(b.grad)

tensor(8034.6221, grad_fn=<DivBackward0>)
tensor([[ 2.0339, -0.0799, -0.0543],
        [ 1.0528,  0.5236,  0.5564]], requires_grad=True)
None
tensor([-0.6229,  1.7652], requires_grad=True)
None


In [8]:
loss.backward()

In [9]:
print(loss)
print(w)
print(w.grad) #dloss/dw
print(b)
print(b.grad) #dloss/dw


tensor(8034.6221, grad_fn=<DivBackward0>)
tensor([[ 2.0339, -0.0799, -0.0543],
        [ 1.0528,  0.5236,  0.5564]], requires_grad=True)
tensor([[7684.7734, 5956.1152, 4098.7207],
        [6471.2271, 5814.3936, 3789.3142]])
tensor([-0.6229,  1.7652], requires_grad=True)
tensor([85.0434, 73.7111])


In [10]:
# Update w = -
# compute loss
for i in range(100):
    preds = model(inputs)
    loss = mse(preds,targets)
    print("Loss before: ", loss)
    loss.backward()
    with torch.no_grad():
        w -=  1e-5*w.grad
        b -=  1e-5*b.grad
        print(w)
        w.grad.zero_()
        b.grad.zero_()
    # compute loss
    preds = model(inputs)
    loss = mse(preds,targets)
    print("Loss After: ",loss)

Loss before:  tensor(8034.6221, grad_fn=<DivBackward0>)
tensor([[ 1.8802, -0.1991, -0.1362],
        [ 0.9234,  0.4073,  0.4806]], requires_grad=True)
Loss After:  tensor(4717.4839, grad_fn=<DivBackward0>)
Loss before:  tensor(4717.4839, grad_fn=<DivBackward0>)
tensor([[ 1.8267, -0.2338, -0.1619],
        [ 0.8797,  0.3717,  0.4567]], requires_grad=True)
Loss After:  tensor(3943.6362, grad_fn=<DivBackward0>)
Loss before:  tensor(3943.6362, grad_fn=<DivBackward0>)
tensor([[ 1.7807, -0.2607, -0.1826],
        [ 0.8429,  0.3433,  0.4372]], requires_grad=True)
Loss After:  tensor(3412.6653, grad_fn=<DivBackward0>)
Loss before:  tensor(3412.6653, grad_fn=<DivBackward0>)
tensor([[ 1.7410, -0.2810, -0.1992],
        [ 0.8117,  0.3209,  0.4214]], requires_grad=True)
Loss After:  tensor(3045.4841, grad_fn=<DivBackward0>)
Loss before:  tensor(3045.4841, grad_fn=<DivBackward0>)
tensor([[ 1.7063, -0.2960, -0.2125],
        [ 0.7850,  0.3032,  0.4086]], requires_grad=True)
Loss After:  tensor(2788.

Loss before:  tensor(1201.2689, grad_fn=<DivBackward0>)
tensor([[ 1.0667,  0.0309, -0.1899],
        [ 0.4242,  0.4171,  0.3945]], requires_grad=True)
Loss After:  tensor(1186.5681, grad_fn=<DivBackward0>)
Loss before:  tensor(1186.5681, grad_fn=<DivBackward0>)
tensor([[ 1.0584,  0.0377, -0.1883],
        [ 0.4201,  0.4204,  0.3954]], requires_grad=True)
Loss After:  tensor(1172.0524, grad_fn=<DivBackward0>)
Loss before:  tensor(1172.0524, grad_fn=<DivBackward0>)
tensor([[ 1.0502,  0.0444, -0.1868],
        [ 0.4160,  0.4237,  0.3962]], requires_grad=True)
Loss After:  tensor(1157.7188, grad_fn=<DivBackward0>)
Loss before:  tensor(1157.7188, grad_fn=<DivBackward0>)
tensor([[ 1.0420,  0.0511, -0.1853],
        [ 0.4119,  0.4270,  0.3970]], requires_grad=True)
Loss After:  tensor(1143.5653, grad_fn=<DivBackward0>)
Loss before:  tensor(1143.5653, grad_fn=<DivBackward0>)
tensor([[ 1.0338,  0.0577, -0.1838],
        [ 0.4079,  0.4303,  0.3978]], requires_grad=True)
Loss After:  tensor(1129.

In [ ]:
# Dataset and 