In [1]:
import torch

In [3]:
x = torch.empty(5,3)
print(x)

tensor([[8.4490e-39, 9.2755e-39, 1.0469e-38],
        [9.6429e-39, 9.4592e-39, 7.3470e-39],
        [7.7144e-39, 1.0469e-38, 9.5510e-39],
        [9.9184e-39, 9.0000e-39, 9.0000e-39],
        [1.0561e-38, 9.0919e-39, 4.2246e-39]])


In [4]:
x = torch.rand(5,3)
print(x)

tensor([[0.0971, 0.5681, 0.8474],
        [0.0532, 0.2821, 0.1098],
        [0.2145, 0.1734, 0.2764],
        [0.6890, 0.0035, 0.1905],
        [0.6222, 0.4026, 0.8408]])


In [9]:
x = torch.zeros(5,3, dtype=torch.long)
print(x)
print(x.size())

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
torch.Size([5, 3])


In [7]:
x = torch.tensor([5.4, 3])
print(x)

tensor([5.4000, 3.0000])


In [8]:
x.size()

torch.Size([2])

In [10]:
# Operations
x = torch.rand(5,3)
print(x)
y = torch.rand(5,3)
print(x+y)

tensor([[0.1251, 0.7001, 0.2685],
        [0.0208, 0.5867, 0.9013],
        [0.0727, 0.0958, 0.2670],
        [0.5793, 0.7869, 0.7062],
        [0.1376, 0.2242, 0.1378]])
tensor([[0.4237, 1.4195, 1.2113],
        [0.2986, 0.6089, 1.1858],
        [1.0644, 0.5065, 0.7625],
        [0.8223, 0.8190, 0.7949],
        [0.1999, 0.2539, 0.7678]])


In [11]:
print(torch.add(x, y))

tensor([[0.4237, 1.4195, 1.2113],
        [0.2986, 0.6089, 1.1858],
        [1.0644, 0.5065, 0.7625],
        [0.8223, 0.8190, 0.7949],
        [0.1999, 0.2539, 0.7678]])


In [18]:
results =torch.empty(5,3)
r=torch.add(x, y, out=results)
print(results)
print(r)

tensor([[0.5488, 2.1196, 1.4799],
        [0.3194, 1.1957, 2.0871],
        [1.1371, 0.6023, 1.0295],
        [1.4015, 1.6059, 1.5011],
        [0.3375, 0.4782, 0.9056]])
tensor([[0.5488, 2.1196, 1.4799],
        [0.3194, 1.1957, 2.0871],
        [1.1371, 0.6023, 1.0295],
        [1.4015, 1.6059, 1.5011],
        [0.3375, 0.4782, 0.9056]])


In [16]:
y.add_(x)

tensor([[0.4237, 1.4195, 1.2113],
        [0.2986, 0.6089, 1.1858],
        [1.0644, 0.5065, 0.7625],
        [0.8223, 0.8190, 0.7949],
        [0.1999, 0.2539, 0.7678]])

In [19]:
print(x[:,1])

tensor([0.7001, 0.5867, 0.0958, 0.7869, 0.2242])


In [21]:
print(x)
x.view(15)

tensor([[0.1251, 0.7001, 0.2685],
        [0.0208, 0.5867, 0.9013],
        [0.0727, 0.0958, 0.2670],
        [0.5793, 0.7869, 0.7062],
        [0.1376, 0.2242, 0.1378]])


tensor([0.1251, 0.7001, 0.2685, 0.0208, 0.5867, 0.9013, 0.0727, 0.0958, 0.2670,
        0.5793, 0.7869, 0.7062, 0.1376, 0.2242, 0.1378])

In [22]:
x.view(3,5)

tensor([[0.1251, 0.7001, 0.2685, 0.0208, 0.5867],
        [0.9013, 0.0727, 0.0958, 0.2670, 0.5793],
        [0.7869, 0.7062, 0.1376, 0.2242, 0.1378]])

In [23]:
x.view(-1,5)

tensor([[0.1251, 0.7001, 0.2685, 0.0208, 0.5867],
        [0.9013, 0.0727, 0.0958, 0.2670, 0.5793],
        [0.7869, 0.7062, 0.1376, 0.2242, 0.1378]])

In [27]:
x[0,0].item()

0.12509870529174805

In [9]:
import numpy as np
array = np.random.rand(5,2)
b = torch.from_numpy(array)
b

tensor([[0.9071, 0.3202],
        [0.3807, 0.8470],
        [0.7132, 0.5341],
        [0.9337, 0.0098],
        [0.7534, 0.7273]], dtype=torch.float64)

In [11]:
print(torch.cuda.is_available())

False


In [11]:
# compute differentiation of function 
import torch
x = torch.ones(2,2, requires_grad=True)
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [12]:
print(y.grad_fn)

In [13]:
z = y*y *3 # 3(x+2)^2
out = z.mean() # 
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [18]:
out.backward(torch.tensor(1.0))

In [20]:
out.backward(torch.tensor(2.0))
print(x.grad)

RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.

In [19]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [14]:
a = torch.randn(2,2)
a= ((a*3)/(a -1))
print(a.requires_grad)

False


In [15]:
a.requires_grad_(True)

tensor([[ 0.6511, -2.3115],
        [-0.7677,  1.7439]], requires_grad=True)

In [16]:
print(a.requires_grad)

True


In [17]:
b = (a*a).sum()
print(b.grad_fn)